name: Greetings

on: 
  push:
    branches: no-branch

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating your first issue :tada:'
        pr-message: 'Congrats for your'' first pr :clap::sparkle:'
